load("//zserio:zserio_generator.bzl", "create_model")

create_model(
    name = "generate",
)

alias(
    name = "zserio_bin",
    actual = "@zserio_bin"
)

alias(
    name = "zserio_runtime",
    actual = "@zserio_runtime"
)
